name: atom
channels:
  - conda-forge
dependencies:
  - ambertools
  - configobj
  - openmm
  - openmm-atmmetaforce-plugin
  - openmm-torch >= 1.4
  - openmm-ml >= 1.1
  - nnpops
  - r-base
  - setproctitle
  - torchmd-net >= 0.7

  # PyPI
  - pip
  - pip:
    - .
