name: Publish package

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  publish:
    if: startsWith(github.event.ref, 'refs/tags/')
    uses: acellera/github-actions-workflows/.github/workflows/legacy_publish_private_package.yml@main
    secrets: inherit
